spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&serverTimezone=GMT%2B8
    username: root
    password: 1234

logging:
  level :
    root: warn
    com.myblog.blog: info
  file:
    name: log/blog-pro.log